
// This file is automatically generated. Do not edit it directly.
import { DatabaseManager } from '@/lib/DatabaseManager';
import type { Database } from './types';

// Get the Supabase client from our singleton DatabaseManager
export const supabase = DatabaseManager.getInstance().getClient() as ReturnType<typeof import('@supabase/supabase-js').createClient<Database>>;
